### ISSUE TITLE
Make deployment even easier by not requiring a full database

### ISSUE THREAD

**Issue by hpr1999** [Port39/go-drink#2]
Instead of a postgresql container, we could offer an even simpler one-binary deployment by integrating SQLite.
For this, we'd probably need some work on database independent setup (perhaps using liquibase or something similar).

**Comment by derconno** [comment]
See the referenced pull request for a possible implementation. As long as the database driver is compatible with "database/sql", adding support for it is fairly trivial. HOWEVER: The only sqlite driver that is compatible to "database/sql" requires CGO support, which takes away quite a lot of flexibility... Do we want that?

**Comment by hpr1999** [comment]
So I'll admit I would have to look into the implications of CGO vs plain Go to make an informed decision.
But beforehand, I scoured the web a bit...

There seems to be a translation of SQLite into Go code [here](https://gitlab.com/cznic/sqlite).
At first glance, that looks like it would fix our problem.

**Comment by derconno** [comment]
> the implications of CGO vs plain Go

for our use case, on our hardware, probably not that many. Cross-compilation might become harder and portability suffers, but since we mostly target docker deployments, I think it would be fine. Also, building with CGO disabled would still succeed, only at runtime, with the sqlite driver selected, the application would terminate early. In that case, using it with the postgres driver should (tm) still be possible.

>  There seems to be a translation of SQLite into Go code [here](https://gitlab.com/cznic/sqlite).

Yes, I saw that too. Unfortunately, it is not compatible with "database/sql", so a rewrite of every function that interacts with a database would be required. Honestly, I am not sure if that would be worth the effort, just to avoid CGO.

**Comment by hpr1999** [comment]
> Yes, I saw that too. Unfortunately, it is not compatible with "database/sql", so a rewrite of every function that interacts with a database would be required. Honestly, I am not sure if that would be worth the effort, just to avoid CGO.

Is this really true, or are you perhaps thinking of [this other library](https://github.com/cvilsmeier/sqinn-go)?
I might misunderstand the example, but from the [documentation](https://pkg.go.dev/modernc.org/sqlite#hdr-Connecting_to_a_database):

> To access a Sqlite database do something like

```
import (
	"database/sql"

	_ "modernc.org/sqlite"
)

db, err := sql.Open("sqlite", dsnURI)
```

That looks an awful lot like the same thing we're doing right now, does it not?

**Comment by derconno** [comment]
Jup, you are 100% correct. I have no clue how I overlooked that. The [go wiki](https://go.dev/wiki/SQLDrivers) lists another pure go implementation, which also includes a compatible driver: `github.com/ncruces/go-sqlite3/driver`
I think I will use the latter, as it has a smaller go.sum file. Also, I will go hide under a rock now...

**Comment by hpr1999** [comment]
Ah, no worries, it was an understandable assumption that I'd have just found the other client.
I tried to discern some reasons for using one of the drivers over the other.

A little bit of research into the differences without actual sources or anything:

| Criteria | `cznic/sqlite` | `ncruces/go-sqlite3` |
| -------- | -------------- | -------------------- |
| Active   | yes            | yes                  |
| Contrib  | one main author| one main author      |
| Popularity| meh           | meh                  |
| Testing | looks pretty good | looks pretty good, also officially tested wazero & wasm build  |
| Code     | custom transpiled from C to GO | directly uses sqlite wasm build |
| Runtime  | just plain go? | wasm via wazero      |

So in general `cniz/sqlite` seems a bit more "experimental" insofar as it seems to have a completely own codebase, while `ncruces/go-sqlite3` uses official bindings and only integrates them.

Anecdotally, `cznic/sqlite` still seems to be completely usable even in production and both run a good array of publicly available test suites if the internet didn't lie to me.

So to me, it comes down to whether we mind being (transitively) dependent on having a wasm engine running inside our program.

**Comment by hpr1999** [comment]
I'd lean towards not embedding a wasm engine for this, but I wouldn't terribly mind either way.

**Comment by derconno** [comment]
yeah, let's not do this and just use `cznic/sqlite`
